import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { Inter } from 'next/font/google';
import './globals.css';
import { Box, ThemeProvider } from '@mui/material';
import theme from '@/lib/provider';
import { NavBar } from '@/components/nav-bar';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <Toaster />
            <NavBar />
            <Box
              sx={{
                display: 'flex',
                flexDirection: 'column',
                gap: '4rem',
                justifyContent: 'center',
                marginTop: '64px',
              }}
            >
              {children}
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
